In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


**Creating a Tensor**

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [6]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.8555, 0.5846, 0.1215],
        [0.4998, 0.8710, 0.7939]])

In [10]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## **Tensor** **Shapes**

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    136482322943376,           400874080,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

**Tensor Datatype**

In [18]:
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float64)


tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

In [22]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [23]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

### 2. Element wise operation

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [25]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [26]:
c = torch.tensor([1, -2, 3, -4])

In [27]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [28]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [29]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [30]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [32]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [33]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [34]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [35]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [36]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [37]:
# median
torch.median(e)

tensor(4.)

In [38]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [39]:
# product
torch.prod(e)

tensor(0.)

In [40]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [41]:
# variance
torch.var(e)

tensor(14.9667)

In [42]:
# argmax
torch.argmax(e)

tensor(4)

In [43]:
# argmin
torch.argmin(e)

tensor(2)

### 4. Matrix operations

In [44]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [45]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [46]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [47]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [48]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [49]:
# determinant
torch.det(h)

tensor(-34.0000)

In [50]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

### 5. Comparison operations

In [51]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [52]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [53]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [54]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [55]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [57]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [58]:
# softmax
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [59]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

## Inplace Operations

In [60]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [61]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [62]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [63]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [64]:
torch.relu(m)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [65]:
m.relu_()

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [66]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

## Copying a Tensor

In [67]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [68]:
b = a

In [69]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [70]:
a[0][0] = 0

In [71]:
a

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [72]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [73]:
id(a)

136476756646384

In [74]:
id(b)

136476756646384

In [75]:
b = a.clone()

In [76]:
a

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [77]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [78]:
a[0][0] = 10

In [79]:
a

tensor([[10.0000,  0.0748,  0.9605],
        [ 0.3271,  0.0103,  0.9516]])

In [80]:
b

tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [81]:
id(a)

136476756646384

In [82]:
id(b)

136476756202896